### PR TITLE
Gentoo e.V. moved to Libera

### PR DESCRIPTION
**Pull request by ulm**

### CODE REVIEW

**Comment by ulm** [comment]
What locale should this be sorted in? Apparently sorting in `en_US.utf-8` fails tests.

**Comment by crabbedhaloablution** [comment]
@siraben CI fails for sortedness, but it looks dodgy to sört ö at the very end öf the list.
What's the locale CI öperates under?
I know dealing with locales and sorting in international context quickly devolves into "computer says no". :-)

**Comment by siraben** [comment]
Uh oh! I will take a look at this tomorrow 2021-06-15. Thanks for the contribution, btw.

**Comment by siraben** [comment]
@ulm could you rearrange the list as requested by the CI? I know it's not ideal but I don't want to get into the hairy details about locales and unicode normalization for a silly little list 😝

**Comment by ulm** [comment]
> @ulm could you rearrange the list as requested by the CI? I know it's not ideal but I don't want to get into the hairy details about locales and unicode normalization for a silly little list stuck_out_tongue_closed_eyes

Added as `Gentoo e.V.` now which is pure ASCII.

**Comment by siraben** [comment]
Thanks!

**Pull request merged**
